### PR TITLE
Add configuration parameter to compile only a subset of dia files

### PR DESCRIPTION
**Pull request by albertored**

### CODE REVIEW

**Comment by carlosedp** [comment]
Thanks for your contribution. 
The PR is breaking the current test. Also it would be nice to have an additional test for this specific feature.

**Comment by albertored** [comment]
Strange, all test are ok on my PC

**Comment by albertored** [comment]
Hi, added some test and addressed your comment. On my fork the CI runs just fine

**Comment by carlosedp** [comment]
Thanks!

**Comment by albertored** [comment]
Thank you! Do you think you will publish a new version soon or you wait for other changes?

**Comment by carlosedp** [comment]
Yes, I'll release in a couple of minutes... I was fighting against rebar format trying to use it's plugin but it's messing up with the tests...

**Comment by carlosedp** [comment]
Published 0.8.0

**Pull request merged**
